### ISSUE TITLE
Issues since today

### ISSUE THREAD

**Issue by fltuz** [ebb-earl-co/tidal-wave#267]
Good day,

First of all, I have been using this app and it's been amazing for the last 2-3 years, no issues. Thank you for the experience so far.

Today I noticed a few issues:
1.When I try to download non hi-res stuff on Linux Mint 22.1, only the cover file is downloaded, nothing else. Tried recreating the fireTV device, logged in again on tidal, key was created but the same issue persists.

2.So I thought, let's try to download some high res stuff. 
Keys are short lived (one day) so I was trying to grab a new key on W11 using fiddler classic.
If you start fiddler-classic and then tidal desktop, tidal goes black screen, doesn't want to load, ends up with an error : something went wrong. Looking at fiddler, the connection is not established.
If you start tidal on its own, everything works ok. 
This process has been working for the last 2-3 years flawlessly.
I am suspecting certificate pinning.

3.I had an older android device with Tidal 2.7 on it (not from Play store, the device's own store, it's a FIIO M11), could get a key from there but the same issue happens : only covers downloaded for high res stuff.

I tried everything on a different machine (Also Linux Mint 22.1) by installing tidal-wave from scratch (using the binary), same.

When setting debug, all entries seem normal including Tidal accepting the keys in both cases.

Any ideas?

Thank you in advance,
F

**Comment by ebb-earl-co** [comment]
@fltuz thanks for making an Issue.

At first glance, I do not know what would have changed today. When you say that TIDAL Desktop now does not load when Fiddler is running makes me think that the TIDAL developers found some clever way to inspect what network environment is in place when TIDAL launches. But, that's just a guess.

I haven't had my finger on the pulse of the TIDAL web API development, especially the https://github.com/EbbLabs/python-tidal and https://github.com/exislow/tidal-dl-ng projects. Maybe they've got some up-to-date information for you around TIDAL's API? I'm really not sure!

Please report back if you discover anything, or if this issue ends up being transient. I will, also, look into any changes that TIDAL would have made.

**Comment by fltuz** [comment]
Thanks for looking into this @ebb-earl-co , much appreciated.
Today I tried again with tidal-wave and the same issue happens with cover only as result.
After that I tried with tidal-dl-ng and everything works properly including HIRES.
Did you get a chance to test on your end ?

**Comment by ebb-earl-co** [comment]
@fltuz any update on this? I've just pushed a new version to fix #271 , so maybe your issue was solved? I really don't know

**Comment by fltuz** [comment]
@ebb-earl-co 
I haven't used tidal-wave since then as tidal-dl-ng solved all my problems and I don't even have to extract the token  manually anymore. 
I have just grabbed the release you pushed out yesterday and grabbed a key from my android device (still can't do fiddler on windows, tidal is just black screening) but it's the same : covers only. I tried non-hires (which needs no key) and the same.
If it doesn't happen to anyone else, feel free to close the issue.

**Comment by ebb-earl-co** [comment]
@fltuz thank you for the response
